#!/usr/bin/env python3
"""Build image-production/tools/main.swift from variants.py.

The variant grids are authored once, in variants.py. This emits the Swift program
that judges them with the app's real Sources/Core/TortoisePose.swift, so the
Python design tool and the Swift drop-in check can never disagree about what the
art is.

    python3 gen_posecheck.py          # rewrite main.swift
    swiftc -Onone -o /tmp/posecheck ../../Sources/Core/TortoiseSprite.swift \
           ../../Sources/Core/TortoisePose.swift main.swift && /tmp/posecheck

main.swift is generated and disposable. Edit variants.py, not main.swift.
"""

import sys

HERE = __file__.rsplit("/", 1)[0]
sys.path.insert(0, HERE)

import variants as V  # noqa: E402

PREAMBLE = '''// GENERATED by gen_posecheck.py from variants.py — do not edit by hand.
//
// Judges the candidate tortoise designs against the app's own structural rules,
// by linking the real Sources/Core/TortoisePose.swift and applying the same rules
// TortoisePose.problems enforces. Complements variants.py, which mirrors those
// rules in Python so the design tool still works without a Swift toolchain.
//
// Build:
//   swiftc -Onone -o /tmp/posecheck ../../Sources/Core/TortoiseSprite.swift \\
//          ../../Sources/Core/TortoisePose.swift main.swift && /tmp/posecheck

import Foundation

/// Every rule `TortoisePose.problems` enforces, applied to a raw grid.
/// `name` is used as-is in messages, so pass the pose name.
func gridProblems(_ name: String, _ rows: [String]) -> [String] {
    var out: [String] = []
    let textArea = TortoiseSprite.textArea

    guard rows.count == TortoiseSprite.size else {
        return ["\\(name): \\(rows.count) rows, expected \\(TortoiseSprite.size)"]
    }
    for (index, row) in rows.enumerated() where row.count != TortoiseSprite.size {
        out.append("\\(name): row \\(index) is \\(row.count) wide, expected \\(TortoiseSprite.size)")
    }
    guard out.isEmpty else { return out }

    let grid = rows.map { $0.map { TortoiseCell(rawValue: $0) ?? .empty } }
    func cell(_ x: Int, _ y: Int) -> TortoiseCell {
        guard x >= 0, x < grid.count, y >= 0, y < grid.count else { return .empty }
        return grid[y][x]
    }

    let inked = (0..<grid.count).flatMap { y in (0..<grid.count).map { (x: $0, y: y) } }
        .filter { cell($0.x, $0.y) != .empty }
    guard let seed = inked.first else { return ["\\(name): pose is empty"] }

    var seen = Set<[Int]>([[seed.x, seed.y]])
    var stack = [seed]
    while let point = stack.popLast() {
        for (dx, dy) in [(1, 0), (-1, 0), (0, 1), (0, -1)] {
            let next = (x: point.x + dx, y: point.y + dy)
            guard next.x >= 0, next.x < grid.count, next.y >= 0, next.y < grid.count else { continue }
            guard cell(next.x, next.y) != .empty, !seen.contains([next.x, next.y]) else { continue }
            seen.insert([next.x, next.y])
            stack.append(next)
        }
    }
    let orphans = inked.filter { !seen.contains([$0.x, $0.y]) }
    if !orphans.isEmpty {
        out.append("\\(name): disconnected pixels at "
                   + orphans.map { "(\\($0.x),\\($0.y))" }.joined(separator: " "))
    }

    let eyes = (0..<grid.count).flatMap { y in (0..<grid.count).map { (x: $0, y: y) } }
        .filter { cell($0.x, $0.y) == .eye || cell($0.x, $0.y) == .sleep }
    if eyes.isEmpty { out.append("\\(name): pose has no eye") }
    for eye in eyes {
        let neighbours = [(1, 0), (-1, 0), (0, 1), (0, -1)].map { cell(eye.x + $0.0, eye.y + $0.1) }
        if !neighbours.contains(.skin) {
            out.append("\\(name): eye at (\\(eye.x),\\(eye.y)) touches no skin")
        }
    }

    // The app pins the countdown plate to one fixed rectangle. A redesign is
    // allowed to move it, so a break here is a note, not a failure.
    var plateBreaks = 0
    for y in textArea.y..<(textArea.y + textArea.height) {
        for x in textArea.x..<(textArea.x + textArea.width) where cell(x, y) != .shell {
            plateBreaks += 1
        }
    }
    if plateBreaks > 0 {
        out.append("note \\(name): \\(plateBreaks) cell(s) of the app's fixed plate "
                   + "(x\\(textArea.x)..\\(textArea.x + textArea.width - 1), "
                   + "y\\(textArea.y)..\\(textArea.y + textArea.height - 1)) are not plain "
                   + "shell — expected when a redesign moves the plate")
    }
    return out
}

/// A reel must not be able to destroy pixels that are not part of the head.
///
/// `TortoisePose.reeling` clears the union of the head block's old and new
/// positions, then stamps the block at the new position. Anything that is *not*
/// head inside those columns is gone for good, so a nod would tear a hole in the
/// shell or shear a limb off. Overlap with the new head rows is harmless: the
/// stamp puts a head pixel back.
func overlapProblems(_ name: String, _ rows: [String], reelDistance: Int = 2) -> [String] {
    let cols = TortoisePose.headColumns
    let headCells: Set<Character> = ["h", "e", "z"]

    let headPixels = rows.enumerated().flatMap { y, row in
        row.enumerated().compactMap { x, c -> (Int, Int)? in
            headCells.contains(c) && cols.contains(x) ? (x, y) : nil
        }
    }
    guard let top = headPixels.map({ $0.1 }).min(),
          let bottom = headPixels.map({ $0.1 }).max() else { return [] }

    var cleared = Set<[Int]>()
    var stamped = Set<[Int]>()
    for dy in [-reelDistance, -1, 1, reelDistance] {
        for (x, y) in headPixels {
            cleared.insert([x, y])
            cleared.insert([x, y + dy])
            stamped.insert([x, y + dy])
        }
    }

    var out: [String] = []
    for y in max(0, top - reelDistance)...min(rows.count - 1, bottom + reelDistance) {
        for x in cols {
            let c = Array(rows[y])[x]
            guard c != ".", !headCells.contains(c) else { continue }
            guard cleared.contains([x, y]), !stamped.contains([x, y]) else { continue }
            out.append("\\(name): (\\(x),\\(y)) is '\\(c)' in the head columns "
                       + "x\\(cols.lowerBound)..\\(cols.upperBound), where a nod would delete "
                       + "it and never put it back")
        }
    }
    return out
}

/// The tuck as the app implements it today: everything from column 13 right is
/// cleared and the nub is stamped at a fixed column, because the shipped shell's
/// rim happens to sit exactly at x12.
func tuckedFixedColumn(_ rows: [String], _ nubRow: Int) -> [String] {
    var out = rows.map { Array($0) }
    for y in out.indices {
        for x in TortoisePose.headColumns { out[y][x] = "." }
        if y == nubRow {
            out[y][13] = "h"
            out[y][14] = "z"
        }
        if y == nubRow + 1 {
            out[y][13] = "h"
            out[y][14] = "h"
        }
    }
    return out.map { String($0) }
}

/// The tuck a wider or narrower tortoise needs: find the front rim of the shell
/// per row and leave the nub just inside it, so the sleeping face never ends up
/// floating outside the silhouette.
func tuckedRimAware(_ rows: [String], _ nubRow: Int) -> [String] {
    var out = rows.map { Array($0) }
    var rim = [Int](repeating: 0, count: rows.count)
    for (y, row) in rows.enumerated() {
        rim[y] = row.enumerated().filter { $0.element != "." }.map { $0.offset }.last ?? 0
    }
    for y in out.indices {
        for x in 0..<out.count where x > rim[y] { out[y][x] = "." }
    }
    let inner = max(1, rim[nubRow] - 2)
    if nubRow < out.count {
        out[nubRow][inner] = "h"
        out[nubRow][inner + 1] = "z"
    }
    if nubRow + 1 < out.count {
        out[nubRow + 1][inner] = "h"
        out[nubRow + 1][inner + 1] = "h"
    }
    return out.map { String($0) }
}

/// The same pose set the app derives from its resting grid, so a candidate is
/// judged on every frame the animator can draw rather than only the still.
func poses(from base: [String], rimAwareTuck: Bool = true) -> [(String, [String])] {
    let tuck: ([String], Int) -> [String] = rimAwareTuck ? tuckedRimAware : tuckedFixedColumn
    var blink = base
    blink[7] = String(blink[7].prefix(12)) + "hhzh"
    blink[8] = String(blink[8].prefix(12)) + "hhz."
    return [
        ("resting", base),
        ("blinking", blink),
        ("blinkingUp", TortoisePose.reeling(blink, by: -1)),
        ("blinkingDown", TortoisePose.reeling(blink, by: 1)),
        ("headUp", TortoisePose.reeling(base, by: -2)),
        ("headChew", TortoisePose.reeling(base, by: -1)),
        ("headDown", TortoisePose.reeling(base, by: 1)),
        ("sleeping", tuck(base, 7)),
        ("sleepingBreath", tuck(base, 6)),
    ]
}
'''


def swift_grid(name, rows):
    body = "\n".join(f'    "{row}",' for row in rows)
    return f"let {name}: [String] = [\n{body}\n]\n"


def build():
    parts = [PREAMBLE]
    for variant, swift_name in zip(V.VARIANTS, ["V1", "V2", "V3", "V4", "V5"]):
        parts.append(swift_grid(swift_name, variant["rows"]))

    labels = ", ".join(f'("{v["id"]}", {s})'
                       for v, s in zip(V.VARIANTS, ["V1", "V2", "V3", "V4", "V5"]))
    parts.append(f'''
let candidates: [(id: String, rows: [String])] = [{labels}]

var defects = 0
for candidate in candidates {{
    var judged = overlapProblems(candidate.id, candidate.rows)

    // Genuine defects, judged with a rim-aware tuck. The app's own reel semantics
    // are used either way, so this still catches a nod that tears the silhouette.
    for (poseName, rows) in poses(from: candidate.rows, rimAwareTuck: true) {{
        for problem in gridProblems(poseName, rows) where !problem.hasPrefix("note ") {{
            judged.append(problem)
        }}
    }}

    // The app's tuck clears everything from column 13 right, which suits the
    // shipped shell exactly. Reported separately, because changing it to find the
    // rim is a small edit to TortoisePose.tucked, not a flaw in the drawing.
    var fixedTuckOnly: [String] = []
    for (poseName, rows) in poses(from: candidate.rows, rimAwareTuck: false) {{
        for problem in gridProblems(poseName, rows) where !problem.hasPrefix("note ") {{
            fixedTuckOnly.append("\\(poseName): \\(problem)")
        }}
    }}

    defects += judged.count
    print("\\(judged.isEmpty ? "PASS" : "FAIL")  \\(candidate.id)  \\(judged.count) defect(s); "
          + "\\(fixedTuckOnly.count) extra if the app's fixed-column tuck is kept")
    for problem in judged {{ print("        DEFECT  \\(problem)") }}
    if !fixedTuckOnly.isEmpty {{
        print("        TUCK    \\(fixedTuckOnly.count) sleep-rule problem(s) that vanish if "
              + "the tuck finds the shell rim instead of hardcoding x13")
    }}
}}

print(defects == 0
      ? "\\nEvery candidate is structurally sound across all nine poses."
      : "\\n\\(defects) genuine structural defect(s) found.")
exit(defects == 0 ? 0 : 1)
''')
    return "\n".join(parts)


if __name__ == "__main__":
    path = f"{HERE}/main.swift"
    with open(path, "w") as handle:
        handle.write(build())
    print(f"wrote {path}")
